export const dataDB = [
    {
        id: 1,
        name: "Algo raro",
        urlImages: "./images/algoRaro.png",
        stock: 5,
        price: 1000,
    },
    {
        id: 2,
        name: "Comida sana",
        urlImages: "./images/comidaSana.png",
        stock: 6,
        price: 2000,
    },
    {
        id: 3,
        name: "Ensalada",
        urlImages: "./images/ensalada.png",
        stock: 7,
        price: 3000,
    },
    {
        id: 4,
        name: "Hamburguesa",
        urlImages: "./images/hambur.png",
        stock: 8,
        price: 4000,
    },
    {
        id: 5,
        name: "Perrito",
        urlImages: "./images/perrito.png",
        stock: 9,
        price: 5000,
    },
    {
        id: 6,
        name: "Pescado",
        urlImages: "./images/pez.png",
        stock: 10,
        price: 6000,
    },
    {
        id: 7,
        name: "Pizza",
        urlImages: "./images/pizza.png",
        stock: 11,
        price: 7000,
    },
    {
        id: 8,
        name: "Ramen",
        urlImages: "./images/ramen.png",
        stock: 12,
        price: 8000,
    },
    {
        id: 9,
        name: "Taco",
        urlImages: "./images/taco.png",
        stock: 13,
        price: 9000,
    },
];
